DROP DATABASE IF EXISTS SONGDB;

CREATE DATABASE SONGDB;

use SONGDB;

CREATE TABLE SONG (
    SONG_ID int NOT NULL AUTO_INCREMENT,
    SONG_NAME varchar(255) NOT NULL,
    PRIMARY KEY (SONG_ID)
);

INSERT INTO SONG (SONG_NAME) VALUES ('Happy Birthday');
INSERT INTO SONG (SONG_NAME) VALUES ('Here Comes The Sun');