DROP DATABASE IF EXISTS HANGMAN;

CREATE DATABASE HANGMAN;

use HANGMAN;

CREATE TABLE WORD (
    WORD_ID int NOT NULL AUTO_INCREMENT,
    WORD_SEQ int NOT NULL,
    WORD_TEMPLATE varchar(40) UNIQUE NOT NULL,
    WORD_FULL varchar(50) NOT NULL,
    PRIMARY KEY (WORD_ID)
);

INSERT INTO WORD (WORD_SEQ, WORD_TEMPLATE, WORD_FULL) VALUES (0, 'D_G', 'DOG');
INSERT INTO WORD (WORD_SEQ, WORD_TEMPLATE, WORD_FULL) VALUES (1, 'J___Sc_ipt', 'JavaScript');
INSERT INTO WORD (WORD_SEQ, WORD_TEMPLATE, WORD_FULL) VALUES (2, 'W__Du__i_?', 'WhoDunnit?');